### PR TITLE
Enable points on the multi latency line chart

### PR DESCRIPTION
**Pull request by abooij**
In the latency charts, I find it hard to read the interpolated lines. I'd just like to see the data points. I think just re-enabling the "points" will do the trick.

### CODE REVIEW

**Comment by jberryman** [comment]
The points are just where the x -axis ticks intersect the lines. I don't mind plotting points where there are just two lines, but it needs to look okay with dozens of lines too (e.g. from `scripts/performance_report.sh`).

I imagine what you want is probably just a table of values right? (maybe with colored background green/red)

**Comment by abooij** [comment]
I'd like to have a plot like this
Alt text
with dots on the interpolated graph indicating what is being interpolated.

**Comment by jberryman** [comment]
I understand, but I'm saying that doesn't work visually for the multi line chart you've modified here. there's too much clutter when graphing dozens of lines. Interpolated data are anything that doesn't intersect a vertical tic

**Comment by abooij** [comment]
> I understand, but I'm saying that doesn't work visually for the multi line chart you've modified here. there's too much clutter when graphing dozens of lines. Interpolated data are anything that doesn't intersect a vertical tic

Okay, so how about having the dots when there are at most 3 lines?

**Comment by jberryman** [comment]
> Okay, so how about having the dots when there are at most 3 lines?

sure, that's fine with me. you can just open the index.html file in chrome to experiment with these changes locally

**Comment by abooij** [comment]
> you can just open the index.html file in chrome to experiment with these changes locally

thanks a ton for this tip

I've now changed this PR, so that the data points are only plotted when showing at most 3 lines. What do you think?

**Pull request merged**
